### ISSUE TITLE
Time values in RFC5545 don't allow milliseconds

### ISSUE THREAD

**Issue by tisdall** [svycal/calex#2]
According to [RFC5545 3.3.12](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.12) a time value has a resolution of seconds.  [Calex currently truncates to milliseconds](https://github.com/svycal/calex/blob/20c35efb6bd807b77e184291b4d6f0df29065ac3/lib/calex/encoder.ex#L33) and results in a content line such as `DTSTAMP:20241121T170910.228Z` which is not valid.  Changing it to `|> DateTime.truncate(:second)` would solve the problem.

Are PRs welcome?

**Comment by derrickreimer** [comment]
PRs definitely welcome! Thanks @tisdall
